#!/usr/bin/env bash


start_learninglocker() {
    # enter the service dirctory
    pushd /learninglocker

    # start the service
    pm2 start pm2/all.json

    # go back to the previous directory
    popd
}


start_xapi() {
    # enter the service dirctory
    pushd /xapi-service

    # start the service
    pm2 start pm2/xapi.json

    # go back to the previous directory
    popd
}


start_nginx() {
    export DOLLAR='$'

    export NGINX_PORT="${NGINX_PORT:-80}"
    export SITE_URL="${SITE_URL:-_}"

    export UI_PORT="${UI_PORT:-3000}"
    export UI_HOST="${UI_HOST:-127.0.0.1}"

    export API_PORT="${API_PORT:-8080}"
    export API_HOST="${API_HOST:-127.0.0.1}"

    export XAPI_PORT="${XAPI_PORT:-8081}"
    export XAPI_HOST="${XAPI_HOST:-127.0.0.1}"

    envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/sites-enabled/default

    nginx -g 'daemon off;' "$@"
}


main() {
    start_learninglocker

    start_xapi

    start_nginx "$@"
}

# fail fast
set -eo pipefail

# execute the main function
main "$@"
