#!/usr/bin/env bash

main() {
    export DOLLAR='$'

    export NGINX_PORT="${NGINX_PORT:-80}"
    export SITE_URL="${SITE_URL:-_}"

    export UI_PORT="${UI_PORT:-3000}"
    export UI_HOST="${UI_HOST:-127.0.0.1}"

    export API_PORT="${API_PORT:-8080}"
    export API_HOST="${API_HOST:-127.0.0.1}"

    export XAPI_PORT="${XAPI_PORT:-8081}"
    export XAPI_HOST="${XAPI_HOST:-127.0.0.1}"


    envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf

    nginx -g 'daemon off;' "$@"
}


set -eo pipefail

main "$@"
